language: go
go: 1.13.6

jobs:
  include:
    - stage: test
      name: Build
      script: make build
    - stage: test
      name: Test
      script: make test
    - stage: test
      name: Vet
      script: make vet
    - stage: test
      name: Docker Build
      script: make docker_build

services:
  - redis-server
